env:
  browser: true
  es6: true
extends: 'eslint:recommended'
globals:
  atom: false
  beforeEach: false
  describe: false
  expect: false
  it: false
  jasmine: false
  runs: false
  waitsForPromise: false
parserOptions:
  sourceType: module
rules:
  array-bracket-spacing:
    - 1
    - never
  arrow-spacing:
    - 1
  block-scoped-var:
    - 2
  block-spacing:
    - 1
    - always
  brace-style:
    - 1
    - allman
    - allowSingleLine: true
  camelcase:
    - 1
  comma-spacing:
    - 1
  comma-style:
    - 1
  computed-property-spacing:
    - 1
  consistent-return:
    - 1
  dot-notation:
    - 1
  eol-last:
    - 1
  eqeqeq:
    - 2
  func-call-spacing:
    - 1
  indent:
    - 1
    - tab
  key-spacing:
    - 1
  new-cap:
    - 1
  new-parens:
    - 1
  no-catch-shadow:
    - 2
  no-duplicate-imports:
    - 1
  no-else-return:
    - 1
  no-empty-function:
    - 1
  no-extra-bind:
    - 1
  no-extra-parens:
    - 1
  no-implicit-coercion:
    - 1
  no-invalid-this:
    - 2
  no-labels:
    - 2
  no-lone-blocks:
    - 1
  no-lonely-if:
    - 1
  no-mixed-spaces-and-tabs:
    - 1
    - smart-tabs
  no-multiple-empty-lines:
    - 1
    -
        max: 1
        maxEOF: 1
        maxBOF: 1
  no-multi-spaces:
    - 1
  no-nested-ternary:
    - 1
  no-new-object:
    - 1
  no-new-wrappers:
    - 2
  no-return-assign:
    - 2
  no-self-compare:
    - 1
  no-shadow:
    - 2
  no-shadow-restricted-names:
    - 2
  no-trailing-spaces:
    - 1
  no-unneeded-ternary:
    - 1
  no-use-before-define:
    - 2
  no-useless-call:
    - 1
  no-useless-computed-key:
    - 1
  no-useless-concat:
    - 1
  no-useless-escape:
    - 1
  no-useless-rename:
    - 1
  no-unsafe-negation:
    - 1
  no-var:
    - 2
  no-void:
    - 2
  no-whitespace-before-property:
    - 1
  object-curly-spacing:
    - 1
  operator-assignment:
    - 1
  padded-blocks:
    - 1
    - never
  prefer-const:
    - 1
  prefer-numeric-literals:
    - 1
  prefer-rest-params:
    - 1
  prefer-spread:
    - 1
  quotes:
    - 1
    - single
  rest-spread-spacing:
    - 1
  semi:
    - 1
    - always
  semi-spacing:
    - 1
  space-before-function-paren:
    - 1
    - never
  space-in-parens:
    - 1
  space-infix-ops:
    - 1
  template-curly-spacing:
    - 1
  valid-jsdoc:
    - 2
  yoda:
    - 1
